### PR TITLE
Add yml config

### LINKED ISSUE #51: Create Github Pages
We can create Github Pages for this project, which will be available on https://rajatgoyal715.github.io/Puzzle15

### PR DESCRIPTION
**Pull request by rajatgoyal715**
Closes #51

### CODE REVIEW

**Comment by therealshabi** [comment]
Is that it? Only one line change?

**Comment by rajatgoyal715** [comment]
> Is that it? Only one line change?

Yes

**Comment by therealshabi** [comment]
> > Is that it? Only one line change?
> 
> Yes

Again this should've been directly committed to the `master`, small changes should be committed directly to the master. The purpose of the review is to analyze the code for any bad code practice or any edge cases, which mostly happens in big changes, let alone in a single line :P This again increases development time (waiting for review to be approved and then merge) So please make sure you commit these kinds of small changes directly to the `master` branch, after all, it's your app ;)

**Comment by rajatgoyal715** [comment]
> > > Is that it? Only one line change?
> > 
> > 
> > Yes
> 
> Again this should've been directly committed to the `master`, small changes should be committed directly to the master. The purpose of the review is to analyze the code for any bad code practice or any edge cases, which mostly happens in big changes, let alone in a single line :P This again increases development time (waiting for review to be approved and then merge) So please make sure you commit these kinds of small changes directly to the `master` branch, after all, it's your app ;)

You are correct this time as well. But I have protected the default branch `master` so that no one can commit directly into the master branch without creating a pull request first and getting it approved by at least one reviewer. I know that this might also be debatable, but I thought of trying this branch protection feature.

**Comment by therealshabi** [comment]
Ev

> > > > Is that it? Only one line change?
> > > 
> > > 
> > > Yes
> > 
> > 
> > Again this should've been directly committed to the `master`, small changes should be committed directly to the master. The purpose of the review is to analyze the code for any bad code practice or any edge cases, which mostly happens in big changes, let alone in a single line :P This again increases development time (waiting for review to be approved and then merge) So please make sure you commit these kinds of small changes directly to the `master` branch, after all, it's your app ;)
> 
> You are correct this time as well. But I have protected the default branch `master` so that no one can commit directly into the master branch without creating a pull request first and getting it approved by at least one reviewer. I know that this might also be debatable, but I thought of trying this branch protection feature.

Even the owner can't commit directly? Strange if yes

**Pull request merged**
